### ISSUE TITLE
Export formatted data from V2 Admin or with linking script

### ISSUE THREAD

**Issue by kepstein23** [Watts-Lab/deliberation-empirica#126]
As a developer, I want a way to export data from the tajriba.json file yet.

A script that just formats the data in an easier-to-understand way would be sufficient (and possibly preferred, so that we can include it in testing and in an automatic data extraction pipeline).

**Comment by kepstein23** [comment]
NodeID tracks each player in tajriba.json

**Comment by JamesPHoughton** [comment]
When we push new code to main, we will probably overwrite the tajriba.json on digitalocean. We might make a check action to see that a hash of the current tajriba.json matches a hash in our raw data dumps list, and if not to get the most recent version and save it in https://github.com/Watts-Lab/deliberation-data-private/raw

**Comment by kepstein23** [comment]
id in participant line is the same as createdById in Survey line
