### ISSUE TITLE
Cypress test what happens if a player drops during discussion

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#162]

**Comment by kepstein23** [comment]
What is expected behavior for this @JamesPHoughton

**Comment by JamesPHoughton** [comment]
The rest of the players should be able to continue as normal.

**Comment by JamesPHoughton** [comment]
We don't currently have a way to boot players from a discussion in automated tests. However, manual tests work fine. If one player leaves, the others proceed as normal. If everybody quits from the video training, they can go back in and the experiment is still there. If a single player drops from the discussion room they can reenter no problem. If everybody drops from discussion room, the room restarts if they join up again.
