### ISSUE TITLE
Force browser refresh code

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#194]
Becca found that she was seeing an old version of the intro because it was cached in her browser, how do we not have that?

**Comment by Alan-Qiao** [comment]
The easiest solution is to add a version param to the url for loading scripts into the html. This would mean that we will need to add a different version number to the script **manually** for every new build we push to digitalocean.

Here's index.html
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Empirica Experiment</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx?version=20220728"></script>
  </body>
</html>
```
One option is to use the date, i.e. 20220728

**Comment by JamesPHoughton** [comment]
Should be able to put this in github action or dockerfile

**Comment by JamesPHoughton** [comment]
Closed in https://github.com/Watts-Lab/deliberation-empirica/pull/226

**Comment by Alan-Qiao** [comment]
This isn't actually working. Is there someway to overcome the main protection? @JamesPHoughton 

![Image](https://user-images.githubusercontent.com/33496657/180911971-f4037f1d-c6f1-4ade-a21b-ae1eb264ceff.png)
