### ISSUE TITLE
Add Training Video

### ISSUE THREAD

**Issue by kepstein23** [Watts-Lab/deliberation-empirica#206]

**Comment by Alan-Qiao** [comment]
Where are we displaying the training video? In the "Get to know you" discussion stage or as an extra stage in the intro?

**Comment by Alan-Qiao** [comment]
Also is Neta going to give us a physical video or a youtube link? I'm leaning towards just coding a lean html solution, but I need to use two different elements depending on whether it's a file or youtube link

**Comment by JamesPHoughton** [comment]
Completed in https://github.com/Watts-Lab/deliberation-empirica/pull/216
