### ISSUE TITLE
Find a 5-minute training video on listening/deliberation

### ISSUE THREAD

**Issue by kepstein23** [Watts-Lab/deliberation-empirica#207]

**Comment by kepstein23** [comment]
Look on youtube for testing until we get our video

**Comment by isaacgat** [comment]
https://www.youtube.com/watch?v=7wUCyjiyXdg

**Comment by JamesPHoughton** [comment]
Works for now! The preamble and promotion of his other work is a bit annoying, but we'll at least be able to demonstrate the concept in a reasonable way.
