### ISSUE TITLE
Launch EB environment as part of deploy workflow

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#21]
The current [deploy action](https://github.com/Watts-Lab/deliberation-empirica/blob/main/.github/workflows/deploy.yml) to launch Empirica on Elastic Beanstalk requires us to go into the AWS console and create an environment manually. We want to be able to create the Elastic Beanstalk environment that empirica will run inside as part of the deploy action, so that we can keep the environment de-provisioned most of the time (as we'll only be running experiments once a week to begin with) and launch it automatically when we are ready to deploy to it. 

- Should be able to work in a branch off of 'main'. 
- I'm not sure if the `ubuntu-latest` github action runner that we're using has access to the EB CLI, may need to work out how to make that available to the action.

## Resources
[Creating Elastic Beanstalk environments with the AWS CLI](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/environments-create-awscli.html)

## Related
- Part of the larger issue to deploy to AWS from a GitHub action: https://github.com/Watts-Lab/deliberation-empirica/issues/11
- Probably makes sense to think about this at the same time as: https://github.com/Watts-Lab/deliberation-empirica/issues/17

**Comment by yli12313** [comment]
I just came back from my event... I spent quite a lot of time looking at this today. I got the GitHub Action to create an environment through CLI commands. It works, but for whatever reason it keeps terminating the environment as soon as it's created. I solved 3 problems today, but encountered a 4th. Realized the GitHub action needs to interface with the AWS EB role. But now I'm trying to solve this issue right now.
![image](https://user-images.githubusercontent.com/7104719/167744102-1e1194cd-5328-42b1-b087-401295f8eab6.png)

**Comment by yli12313** [comment]
Ok, been grinding some more. I'm going to need some support tomorrow from everyone. I got it to launch, but I seem to solve one problem and there's 3 others that appear. 

![image](https://user-images.githubusercontent.com/7104719/167751288-0cc5ebe1-bba9-4a17-9345-b5a64605952a.png)

![image](https://user-images.githubusercontent.com/7104719/167751320-6d5aa641-f93a-44e7-87a1-f44a88429171.png)

**Comment by JamesPHoughton** [comment]
We may be able to use an environment manifest to configure the environments: https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/environment-cfg-manifest.html

**Comment by JamesPHoughton** [comment]
Closing in favor of current digitalocean workflow
