### ISSUE TITLE
Integrate ESLint into Workflow?

### ISSUE THREAD

**Issue by Alan-Qiao** [Watts-Lab/deliberation-empirica#210]
Perhaps it's a good idea to add ESLint to deliberation-empirica so that we can catch typos and other compile bugs more easily and also standardize our code style to make it easy for fall RA's to take over.

Here are some options for style guides to use with ESLint:
1. airbnb style
   - Probably the most popular style guide, very comprehensive and most rules are reasonable
   - Used in CIS350, CIS197
   - https://github.com/airbnb/javascript
2. eslint-plugin-react
   - Styling plugin specifically for react
   - Probably should use this in conjunction with other JS main guides we choose
   - https://www.npmjs.com/package/eslint-plugin-react
3. eslint-plugin-cypress
   - Released by cypress, useful for getting suggestions in writing cypress tests
   - https://www.npmjs.com/package/eslint-plugin-cypress
4. JS Standard Style
   - minimal style guide, but can autoformat any styling issues on its own without eslint
   - https://standardjs.com/
   - https://www.npmjs.com/package/eslint-config-standard
5. Google Style
   - style guide used by Google dev team
   - plugin has not been updated since 2020
   - https://github.com/google/eslint-config-google

Thoughts on which to use? I can take care of the setup work.

**Comment by JamesPHoughton** [comment]
Use in CIS350 is a big plus from a dev perspective. Are the options mutually exclusive? Ie, can we use 1,2 and 3 together?
Also, what will this require everyone to do? I assume there will be a Github PR check involved, and some tooling setup on everyone's dev machine?

If the tooling setup is significant, we might consider ending the summer with a final PR to get everything in the proper style, and then requiring it going forwards?

**Comment by Alan-Qiao** [comment]
1,2,3 can be used together. 1, 4, 5 are mutually exclusive.

There will be 1 PR required to include eslint in package.json and to add a eslint config file.

As for individual setup, all that is required is the installation of the ESLint extension on VSCode, and to install the relevant eslint packages through npm install. (This would need to be installed locally, not through docker)

I would personally recommend installing eslint package globally `npm install -g eslint`, but if that proves too much work, a project-specific installation can be easily achieved by just running `npm install`.

**Comment by JamesPHoughton** [comment]
> to install the relevant eslint packages through npm install. (This would need to be installed locally, not through docker)

What folder would they live in? why can't they be on docker? Currently, only `cypress` has npm installs locally...

**Comment by Alan-Qiao** [comment]
We have decided on implementing ESLint, using a combination fo 1+2+3.
The issue will remain open as an ongoing discussion of specific rules that might want to be enforced/disabled.

**Comment by Alan-Qiao** [comment]
`linebreak-style`
I decided to disable this rule because github by default uploads to remote with crlf line endings, so it doesn't make sense to enforce lf endings

`semi`
Should we enforce semicolons at end of every statement or no? It doesn't matter to the compiler

`quotes`
This rules enforces single quotes arround strings. I personally like this one because it helps avoid silly errors like forgetting to escape double quotes, but thoughts?

`import/prefer-default-export`
This rules enforces the use of default export `export default function smth {` when there is only one export in the file. I've been using this one in the past, but I guess there is also an argument that it is harder to mess up imports if every import is wrapped in object destructuring syntax

`object-curly-newline`
This one is interesting. https://eslint.org/docs/latest/rules/object-curly-newline The default complains when a object has 3+ attributes and wants you to add line breaks. I'm guessing the argument for this rule is that when objects get too long, it might be hard to read what's in the object and what's not at a quick glance, or just to prevent the line from getting too long. I don't feel strongly either way about this one. One option we can do is to just set it to check for consistency (content and braces all on the same line or content and braces each on their own line)

**Comment by JamesPHoughton** [comment]
1. can ignore crlf
2. yes enforce semicolons
3. yes enforce single quotes
4. ambivalent? Prefer named exports to default exports.
5. I like multiline: https://eslint.org/docs/latest/rules/object-curly-newline#multiline

**Comment by JamesPHoughton** [comment]
Nicolas recommends "prettier". You can add it as a hook. "Husky" is a good tool to run before commits (on hooks). 
Add prettier as a dev dependency in package.json, set it up as a pre-commit hook. 
 
One of our objective functions is giving coders fast feedback so that they can learn how to be better coders. If we just used an automated tool that did formatting for you, we'd get nice code, but we might not develop as much as coders. Having ESLint enforce a style in a way that is really visible to the coder makes sense. Not sure if we also need prettier as well, in that case.

**Comment by JamesPHoughton** [comment]
closed by https://github.com/Watts-Lab/deliberation-empirica/pull/251
