### ISSUE TITLE
Make feedback button float

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#241]
Make button smaller so that it won't overlap with page content, too

**Comment by JamesPHoughton** [comment]
Looks like there's still some content overlap: 
![image](https://user-images.githubusercontent.com/4304478/182648981-6a734bfd-bf25-4e81-ad9c-3593ad33e5fb.png)

**Comment by JamesPHoughton** [comment]
Not sure if this is something we should fix by moving the button, or by moving the text...

**Comment by Alan-Qiao** [comment]
Hmm good question. Moving the tex would probably mean adding a top padding to every page, but that feels like the same as just having the button as its own div above everything else. How about bottom left corner?

**Comment by JamesPHoughton** [comment]
Lets try it. Or could we make the button smaller? Just say "Feedback"? Or make it vertical, and attached to the edge?
![image](https://user-images.githubusercontent.com/4304478/182651685-4ddec9d2-e78e-4d37-b70c-89eda0f81b50.png)

**Comment by Alan-Qiao** [comment]
I like this vertical idea. Feels less intrusive even if it does cover some
content occasionally. We might need to implement some way to allow content
to scroll clear of that vertical button.

Let me try it

**Comment by JamesPHoughton** [comment]
Can we fix the button to a particular point in the window, and have the content scroll behind it, like the empriica elephant does?

**Comment by Alan-Qiao** [comment]
#258
