### ISSUE TITLE
📝 Notes on meetings with Daily

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#257]
# background
Eyeson has significant latency and some headaches around how the video is displayed (ie, it's all formatted on the server side, and so participants views are not mirrored). Daily is a more mature service that we will probably pay a little bit more for.

# question
Should we abandon eyeson in favor of Daily?

# Discussion with daily folks:

## About us:
- [Computational Social Science Lab at Upenn](https://css.seas.upenn.edu/) uses online lab experiments to answer questions about human behavior and the behavior of groups. 
- Study of how small groups deliberate: Lots of theory, but the best interventions depend on context: group attributes, topic attributes. Experiments have been too expensive to test different strategies in different contexts.
- Our technical challenge is to **dramatically reduce the cost of running small-group deliberation experiments**, so that we can [run high-throughput experiments](https://css.seas.upenn.edu/project/group-dynamics/) to explore how interventions vary with context. 
- Testing 1) training 2) procedures 3) feedback interventions.
- Building a collaboration of researchers using a shared infrastructure, and a shared dataset. If we are successful, what we build will be used by many scientists across our field. How many social science questions involve small groups having conversations? A lot!
- Initially paid participants (n~1000-3000) working towards larger-scale studies with volunteer participants (n ~10,000-50,000)
- Working prototype in this repo. Mostly react.

### Pricing
- is there a fee to record directly to our S3 bucket?
- is there an academic discount?

### Rooms model
- programmatically create rooms and assign individuals to them? 
- multiple simultaneous rooms? (Limits on number of rooms? Recruitment for experiments is easier with larger, infrequent batches. Upper limit for initial tests is probably ~200 simultaneous rooms)
- works in the browser, no downloads needed?
- no registration for participants?

### Recording
- can we get a separate audio stream for each participant?
- attributed audio transcription?

### Technical
- What does daily do to reduce latency? 
- How much can we customize client side UI? Difference between Prebuilt and DIY components? Example code?
- Do you have callbacks that tell when a participant is speaking?
- Is there a "test call"(video/audio device check) we can embed?
- Exporting performance metrics at call end?

**Comment by JamesPHoughton** [comment]
- Parnership with deepgram for transcription in several languages
- speaker-meter is a common request. Do expose client-side events about when a speaker starts talking. 
- Every daily call is supported by call quality metrics, every 15 seconds. one of the metrics is "audio energy" which tells you what each participant's audio levels were for the 15 seconds.
- Could connect with a sentiment tool to analyze things real time.

- .01349 cost for recording applies to streaming to our own S3 bucket, but we don't pay the storage fee.
- No explicit academic pricing structure, first 10000 minutes are free. Enough for testing. If we feel like we have a good idea of approximate minutes we'll spend, come back and talk about pricing. Will work with us on pricing, have a startup program that our component would be eligible for. 

## rooms model
- Use API to create rooms and assign people to them
- Default simultaneous rooms is 10,000
- Streaming to S3 is a composited mp4 file,  other option to get raw streams separate, video and audio, "RTP tracks". Think that pricing is the same. Working on raw-tracks which go straight to the cloud. 
- transcription is built into the js API, using deepgram. Extra cost. https://deepgram.com/pricing/
- Based on a mesh SFU infrastructure. Different media servers in different parts of the world, that then connect to each other. 
- https://docs.daily.co/guides/architecture-and-monitoring/intro-to-video-arch#the-architecture-of-a-room-p2p-vs-sfu-calls
- "Daily community" a monitored forum. 
- have "hair check" UI, can separate from the main body of the call
-

**Comment by JamesPHoughton** [comment]
Responses from Kyle:

> 1. We currently do not offer stubs. I will bring this up internally as a feature request. I know it is something we would like to offer. 
> 2. Recordings are just a flat rate for the duration of the session. It does not matter the number of participants and you wouldn't pay multiple times for the same session. Just a flat rate for each session/cohort that would take place.

**Comment by JamesPHoughton** [comment]
The support from Daily seems to be substantially better than eyeson, so our likelihood of success or recovering from failure is much better. They seem less likely to go out of business.

**Comment by JamesPHoughton** [comment]
When does the recording start and stop? What do we get billed for?

**Comment by JamesPHoughton** [comment]
Chat with Kyle about startup program
- we would be considered a startup for the purposes of the package.
- Daily provides premium support plus credit toward the service to be used within 12 months
- After 12 months, have regular support, or pay for premium support
- Submitted startup program form.

Daily tech team meets thursdays, they often block time to look at customer's products/code. We might create an issue which talks through our integration and invite their comments, and then down the road do the same again with our testing stubs.

**Comment by JamesPHoughton** [comment]
Questions for 10/17:
- Why do we need s3 bucket to enable versioning? Do we expect to pay much more because of this?
-

**Comment by Alan-Qiao** [comment]
10/17 Debugging Sessions
### Haircheck Issues
 - source of problem may have been React recreating the DailyCallObject on each update to the component
 - probably either wrap into a state, a ref, or a callback
 - Consider this demo as a [reference](https://github.com/daily-demos/call-object-react/blob/d85bfa4e12584a0256f9c803fd490819ef85580f/src/components/App/App.js#L49)
 - Should resolve issues with participants(), event-listeners, and simplify track switching
### Tracking When Each Participant is Speaking
 - look for changes in audio energy, sharp increase probably start talking, which is available through WebRTC stats
 - [example](https://dailyco.notion.site/Audio-Level-Activity-Indicator-97fb645c20304d26ab7f19114ae44c6b) of tracking audio energy of local participant with daily
 - Can also use activeSpeakerChange event to record active speaker
 - This is best done in sfu-mode, where activeSpeaker is calculated through Daily servers rather than local browsers
### Recording Button
 - Chad said he will follow up on whether there is a way to disable recording button in prebuilt
 - No simple public endpoint available to disable it for sake of privacy concerns
### AWS Issues
 - Did not get a chance to walk through the issue in meeting
 - Will follow-up with daily support team and Kyle through email communication
