### ISSUE TITLE
Test Implementation of Daily

### ISSUE THREAD

**Issue by Alan-Qiao** [Watts-Lab/deliberation-empirica#260]
We are looking to replace EyesOn for the video discussion component as the latency is drowning out any other signals we may observe.
We want to test Daily.co as a replacement. Daily was able to meet all the specifications in #257.

**Comment by JamesPHoughton** [comment]
We're going to try to implement with Daily, considering it as a provisional implementation based on our experience. We have a meeting with the tech support team set up from Daily on Monday the 19th at 10am, where we can ask questions about the implementation as its going.

**Comment by JamesPHoughton** [comment]
closed in https://github.com/Watts-Lab/deliberation-empirica/pull/292
