### ISSUE TITLE
Implement custom hair-check for intro screens

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#271]
rig up our own custom components to just check camera and mic
one example project for how to do a full custom UI" https://github.com/daily-demos/call-object-react

JS function in daily is just start-camera - manages microphone and camera streams so we don't have to.
may need to make sure we stop the camera, etc.

Save the device ids selected by the user in the hair-check screen and feed it into the actual meeting later

Check in with chad at Daily about right way to extract device ids from haircheck

**Comment by JamesPHoughton** [comment]
Do we need an actual room? if we do, use the game room, but just don't have participants join the room.

**Comment by Alan-Qiao** [comment]
https://github.com/Watts-Lab/deliberation-empirica/commit/f71d2b3feae5e5b5493cd54527adbd8466758c57
Latest commit with "working" implementation of custom hair check.

Some questions that came up:
1. `onGameStart()` runs after intro steps are finished, so kept one permanent room on account called "HairCheckRoom" for all hairchecks, Start-camera does not start an actual session, so can feed infinite players to this link for haircheck
2. Using `setInputDevicesAsync()` does not trigger a `selected-devices-updated` event caught by listener
3. `DailyCallOjbect.participants()` is not defined on subsequent calls (i.e. after selecting a new device), so had to manually get current tracks for local preview using `navigator.mediaDevices.getUserMedia()` with the new `deviceIds`
4. Documentation states that Daily Prebuilt does not take `videoSource` or `audioSource` when a participant joins, so how to pass selected device ids from haircheck to joining the actual discussion?

**Comment by JamesPHoughton** [comment]
closed in https://github.com/Watts-Lab/deliberation-empirica/pull/292
