### ISSUE TITLE
Set up S3 Bucket for streaming deliberation videos

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#272]
We will need an S3 bucket that we can put recordings into. We won't be accessing the videos very frequently, at least at first - just to check them for QC. Eventually we'll want to run automated analysis against them.

I don't know much about how this works, so I have a few questions:

1. Are there different storage tiers with different costs, eg. long duration, high availability, etc.? Which do we want?
2. How do I access the bucket? Is this through the AWS console, logging in as my user?
3. How do we set who within our lab can access the bucket?
4. How do we give Daily permission to write to the bucket? How does Daily know where to write?
5. How do we give other researchers access to the bucket?
6. How do we give our analysis programs access to the bucket?
7. How much does it actually cost to store videos?

@rivera-lanasm

**Comment by Alan-Qiao** [comment]
https://docs.daily.co/guides/products/live-streaming-recording/storing-recordings-in-a-custom-s3-bucket

**Comment by JamesPHoughton** [comment]
Thanks @rivera-lanasm, this is a really helpful breakdown. Can you help me set up the following?

### S3 bucket
- named "wattslab-deliberation-videos" 
- using Intelligent Tiering, everything down to the Archive Instant access tier, but not the asynchronous access levels. 
- daily needs the bucket to enable "bucket versioning" (https://docs.daily.co/guides/products/live-streaming-recording/storing-recordings-in-a-custom-s3-bucket#s3-bucket-configuration-requirements)
- should be in a US location, beyond that whatever is likely to be cheapest

### IAM policy
Daily [has some requirements](https://docs.daily.co/guides/products/live-streaming-recording/storing-recordings-in-a-custom-s3-bucket#creating-an-iam-policy-with-appropriate-permissions) for access permissions, using this policy:
```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "VisualEditor0",
      "Effect": "Allow",
      "Action": [
        "s3:PutObject",
        "s3:GetObject",
        "s3:ListBucketMultipartUploads",
        "s3:AbortMultipartUpload",
        "s3:ListBucketVersions",
        "s3:ListBucket",
        "s3:GetObjectVersion",
        "s3:ListMultipartUploadParts"
      ],
      "Resource": [
        "arn:aws:s3:::your-bucket-name",
        "arn:aws:s3:::your-bucket-name/*"
      ]
    }
  ]
}
```

### IAM role
[Daily docs](https://docs.daily.co/guides/products/live-streaming-recording/storing-recordings-in-a-custom-s3-bucket#creating-an-iam-role-for-daily-to-assume-for-storage)
Trusted Entity Type: AWS Account
Trusted AWS account ID: 291871421005
Required external ID: deliberation
Maximum session duration: 12 hours

We'll need the Amazon Resource Name (ARN) for the role, and the bucket region to include in the daily API calls.

**Comment by rivera-lanasm** [comment]
- ARN's themselves aren't sensitive information, they aren't credentials. 
https://devops.stackexchange.com/questions/11101/should-aws-arn-values-be-treated-as-secrets
  
- I've only used default encryption, I've never read anything encouraging something other than that

- Object lock is a setting you can enable when creating a bucket, and gives option to "lock" objects so they can't be deleted or overwritten. This seems like a similar service as bucket/object versioning. So maybe makes sense to go with one or the other
https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lock.html

- I haven't set up s3 intelligent tiering before, but my understanding is that you can transfer from the default tier to intelligent tiering. I'll have to read more into this

**Comment by JamesPHoughton** [comment]
After reaching out to daily to see why it wasn't working, they replied with:

> On a previous case where we've seen the same error occur, this has been solved by increasing the maximum session duration to 12 hours

I've updated the session length to 12 hours.
