### ISSUE TITLE
Update consent language in empirica

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#279]
In order to share our videos with coders we may recruit from MTurk, we need to make sure participants consent to this use of their data.

I checked in with the penn IRB, who says that the proposed changes do not change the IRB exemption status. (Discussion here: https://github.com/Watts-Lab/deliberation-project/issues/73)

The consent language should be updated as:

![Image](https://user-images.githubusercontent.com/4304478/193840820-0ccda26a-b54a-4a7c-b8bb-44dc2fefdd46.png)

Clean text:
> This activity is part of a scientific experiment to understand the process of group deliberation. Your participation in this study is entirely voluntary, and you may withdraw at any point by closing this browser window.
> During this activity, you may engage in video, audio, or text chat with other study participants. You may be shown instructional material, asked to discuss particular topics, and complete surveys about your experience. We may record your discussion for quality control and analysis. These recordings will be kept secure and confidential. Recordings may be shown to workers we train to analyze and annotate them. We may share recordings under a confidentiality agreement with other researchers.
> Apart from these recordings, the only information we will have is your platform-assigned payment ID (e.g. MTurk worker ID) and the timestamps of your interactions with our site. We will record this ID to allow us to observe participation across sessions. There is no way for us to identify you or contact you outside of the crowd-sourcing platform through which you joined.
> Anonymous data (not including discussion recordings) may be shared publicly. Our aggregate results may be presented at scientific meetings or published in scientific journals.
> You can contact the research team by emailing deliberation-study@wharton.upenn.edu. You can call the University of Pennsylvania Institutional Review Board at 215-898-2614.
> Clicking on the "I AGREE" button indicates that you are at least 18 years of age, understand this agreement, and consent to participate voluntarily.

**Comment by JamesPHoughton** [comment]
Make this consent 1/2, and Netta's as consent 2/2.

**Comment by sky1113** [comment]
UK GDPR is not the same as EU GDPR. The UK incorporated EU GDPR into law as UK GDPR, and it's still very similar to the original. The UK GDPR is covered in the DPA 2018

**Comment by JamesPHoughton** [comment]
New language:

> This activity is part of a scientific experiment to understand the process of group deliberation. Your participation in this study is entirely voluntary, and you may withdraw at any point by closing this browser window.
>
> During this activity, you may engage in video, audio, or text chat with other study participants. You may be shown instructional material, asked to discuss particular topics, and complete surveys about your experience. We may record your discussion to understand how behavior during discussions influences outcomes and for quality control. These recordings will be stored indefinitely on a secure and confidential server. Recordings may be shown to workers we train to analyze and annotate them. We may share recordings under a confidentiality agreement with other researchers. You may contact the research team if you wish to have your video removed.
>
> Apart from these recordings, the only information we will have is your platform-assigned payment ID (e.g. MTurk/Prolific worker ID) and the timestamps of your interactions with our site. We will record this ID to allow us to observe participation across sessions. There is no way for us to identify you or contact you outside of the crowd-sourcing platform through which you joined. 
>
> Anonymous data (not including discussion recordings) may be shared publicly. Our aggregate results may be presented at scientific meetings or published in scientific journals. 
>
> This project has been reviewed by the University of Pennsylvania Institutional Review Board and the School of Psychology and the University of Reading Research Ethics Committee. You can contact the research team by emailing [deliberation-study@wharton.upenn.edu](mailto:deliberation-study@wharton.upenn.edu). You can call the University of Pennsylvania Institutional Review Board at 215-898-2614. You can contact the investigators directly: Dr. Houghton jameshou@wharton.upenn.edu, Prof. Weinstein: [n.weinstein@reading.ac.uk](mailto:n.weinstein@reading.ac.uk), Ms. Moin f.k.t.moin@pgr.reading.ac.uk.
>
> Clicking on the "I AGREE" button indicates that you are at least 18 years of age, understand this agreement, and consent to participate voluntarily.


This includes modifications from @NettaWeinstein's consent document. 

@NettaWeinstein and @TiaMoin - does this work for you guys? Happy to update with changes.

**Comment by JamesPHoughton** [comment]
Question: how to reconcile requirements of collaborating ethics committees between multiple universities.
- Goal: Safety, security, privacy, protection of subjects. (And then - analysis, science)

Language from Reading IRB
> Videotaped research data will be available to members of the research team at the University of Reading and students involved in the project, for the duration of the project. Videos will be deleted once they have been dual-rated by researchers, and transcripts downloaded and de-identified. These data will be accessed by the student researchers directly from the University of Reading’s secure, encrypted storage drive via a password protected link.

> All raw data will be encrypted and stored in a separate, secured location only accessible by the Principal Investigator (Professor Netta Weinstein, Supervisor), the Co-Investigator (Tia Moin, PhD student) and any researchers that need access to the data for analysis purposes. For clarity, identifiable data will never be shared with a third party.

> Videos will be deleted once they have been dual-rated by researchers, and transcripts downloaded and de-identified.

- Add to the instruction set that participants agree to keep the discussion confidential? or to the agreement? - can't guarantee that participants will keep that confidentiality. But "these are the steps that we are taking to ensure confidentiality". We don't give them information to identify each other, but 

- I am willing to keep information in the room
- I will not ask for identifying information about other discussants
- "never reveal personal identification details, for example, your date of birth, address, 
- Saying specific stuff about identity may not influence the discussion so much as "keep things confidential" or "that you wouldn't be comfortable sharing"

**Comment by JamesPHoughton** [comment]
- Add to the instruction set that participants agree to keep the discussion confidential? or to the agreement? We can't guarantee that participants will keep that confidentiality. But "these are the steps that we are taking to ensure confidentiality". We don't give them information to identify each other, and we can ask them not to reveal personal information. One concern is that we don't want them to clam up, as they might if we said "don't share anything wouldn't be comfortable sharing on facebook".

**Comment by markwhiting** [comment]
Check if https://irb.upenn.edu/reliance-agreements is helpful. Also IRB at Penn in general are pretty helpful for working these things out.

**Comment by JamesPHoughton** [comment]
Are there rules explicitly for inter-institution collaboration? Do we need to run the experiment through both institution's IRB? What about when the collaborations are international? Are there guidelines from Penn or other institutions that we could use?

- https://irb.upenn.edu/reliance-agreements
- https://researchservices.cornell.edu/resources/multi-site-and-collaborative-irb-research

Best bet is to ask our IRB, see how we can work out sharing data if penn was to be the IRB of record.

**Comment by markwhiting** [comment]
I think this was done last week so hiding it from https://github.com/orgs/Watts-Lab/projects/8 (of course adjust the status if it needs to return there)

**Comment by JamesPHoughton** [comment]
Currently set up so that we have a default set of consent statements that each support a particular use of data. A different set of statements can be used for US or UK participants to reference GDPR, and these are stored with the scienceData. Additionally, each collaborator can add an "addendum" for things like referencing their school's IRB and giving their contact info.
