### ISSUE TITLE
Add an "about this study" debrief to the "Finished" page

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#305]
As an experiment designer, I want to be able to "debrief" participants following their participation, so that I can support the ethical norms for good conduct of experiments. This should be one or two paragraphs (or bullet points) describing for the participant:

- thanks for participating
- we have your payment info
- why we are running the experiment / how it helps the world
- how their data helps us
- our contact info

**Comment by JamesPHoughton** [comment]
This will need to be a new component in the intro-exit folder, similar to how "lobby" or "playerIdForm" is used.
you'll need to pass it into the `EmpiricaContext` using the `finished` attribute.

```jsx
          <EmpiricaContext
            disableConsent
            playerCreate={DescriptivePlayerIdForm}
            lobby={Lobby}
            introSteps={introSteps} // eslint-disable-line react/jsx-no-bind -- empirica requirement
            exitSteps={exitSteps} // eslint-disable-line react/jsx-no-bind -- empirica requirement
            disableNoGames
            finished={debrief} <-- this here
          >
```

The existing "finished" page is here: https://github.com/empiricaly/empirica/blob/322a3db90b5fc651f2a221b038ee42d3e4a8f3a9/lib/%40empirica/core/src/player/react/Finished.tsx

**Comment by mxumary** [comment]
just summarize the pdf
details to include:
- done with study / thank you
- no need to submit additional payment information
- overview of research study/purpose for study
- if interested, contact us
