### ISSUE TITLE
How to find your id button on intro page

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#354]
Edit the player sign-in page to help participants find their ids if necessary.

"Not sure what your ID is? here's how to find it on <MTurk>, <Polific>, <Wharton Behavioral Lab>. "

### SONA
How to find your WBL Lab ID:  
Log into Sona (https://upenn-wbl.sona-systems.com/) and click “My Profile” in the upper right corner. The 4-digit number next to Identity Code is your Lab ID.

**Comment by willschulz** [comment]
[Specific instructional text to use for WBL study:]

How to find your WBL Lab ID:  
Log into Sona (https://upenn-wbl.sona-systems.com/) and click “My Profile” in the upper right corner. The 4-digit number next to Identity Code is your Lab ID.
