### ISSUE TITLE
Launch multiple test players with cypress

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#36]
When we want to test a 2-player game, we will need to have cypress operate two separate browser tabs at the same time, so that it can pretend to be two separate users who coordinate their actions. 

One thing that may be helpful in this is the `playerKey` URL parameter, for example: `http://localhost:3000/?playerKey=alice` opens a new window for a player who empirica will store under the key 'alice', who may not have ever interacted with the game before. We can have cypress visit `http://localhost:3000/?playerKey=alice` and walk through the intro steps, and then visit `http://localhost:3000/?playerKey=bob` and walk through the intro steps for bob. Then if we switch back to `alice` we should be able to continue taking that player's actions...

**Comment by JamesPHoughton** [comment]
@kepstein23 Where did we get to with this last week? I think you were opening an issue to ask the cypress team? I'm sorry for not remembering!

**Comment by kepstein23** [comment]
No worries, I posted on the discussion board here. https://github.com/cypress-io/cypress/discussions/21662

**Comment by JamesPHoughton** [comment]
If you don't get any responses today, it may be worth writing a new question using different language, to see if you can get some attention. You may be able to say something about testing in multiple tabs simultaneously, and give a bit of a shorter description of wanting to test a multiplayer game that requires cypress to take actions on behalf of two players in different browser windows.

**Comment by JamesPHoughton** [comment]
Is this unblocked now? Can we move it to "In Progress" or "Done"?
