### ISSUE TITLE
Cypress test for if players drop out during the discussion

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#383]
Ideally, the game would be able to continue, and if all connected players submit, the stage should submit.

**Comment by JamesPHoughton** [comment]
@JamesPHoughton needs to review a PR for this

**Comment by mxumary** [comment]
PR here https://github.com/Watts-Lab/deliberation-empirica/pull/499

**Comment by JamesPHoughton** [comment]
Complete in https://github.com/Watts-Lab/deliberation-empirica/pull/677/files#diff-cfa48f565edb15a10aba7fd033cfec1cec1323ca12a42b020a151a0a2de6849d
