### ISSUE TITLE
Flag and handle inappropriate behavior

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#4]
Participants always have the ability to leave the experiment by exiting the browser window, but we also want to give them the ability to flag inappropriate or abusive behavior. We will need to decide how to handle these cases in a way that doesn't penalize those who flag the behavior, either by depriving them of earnings or by delegitimizing their concerns.

**Comment by JamesPHoughton** [comment]
Leaving the experiment / ejecting from the discussion could be a really strong signal that the discussion is going poorly, and we want to capture that. Unfortunately, if participants just close the browser window, we can't easily determine if this is because they got fed up, or if they had a technical error. 

Perhaps we should have a "punch out" button (with a popup confirmation) that lets people end the discussion itself, and then proceed to the exit steps (or the next stage). This would let us ask them for more information about why they left the discussion (I was too upset / the other person wasn't being polite vs. we ran out of things to talk about.) and they could still finish and be paid.

**Comment by JamesPHoughton** [comment]
- Leave with the option to return
- Leave and go to a "why did you leave" page

**Comment by sky1113** [comment]
Link to slides: https://docs.google.com/presentation/d/1tqNtPLgchkRN39DhMCFaoxvHAGffafJtpA9TIMev764/edit?usp=drivesdk

**Comment by JamesPHoughton** [comment]
closing in favor of https://github.com/Watts-Lab/deliberation-empirica/issues/423
