### ISSUE TITLE
🤷‍♂️Should we move to an mturk population

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#417]
Reasons not to:
- WBL subsidises students
- Many classic experiments were conducted with student populations, and using this sample would let us replicate those studies
- We already have data on a number of the WBL participants

Reasons to:
- Larger sample pool means we don't worry about "burning" participants 
- It may be easier to construct groups with particular distributions of characteristics when we have more (and more diverse) people to work with
- May be able to use CSS lab panel to get psychometric and demographic data on participants cheaply

**Comment by JamesPHoughton** [comment]
Alternatively, we can move to the WBL panel when we want the student population in particular.

**Comment by xehu** [comment]
Potential reasons to still do something with WBL:
- We've already invested in a long term relationship with WBL, and we don't want that time to be wasted or burn our relationship?

**Comment by JamesPHoughton** [comment]
Closing in favor of Both/And.
