### ISSUE TITLE
Write introduction screens

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#42]
As a participant, I want to quickly learn what will be expected of me during the experiment so that I can be ready to complete it effectively. The standard way for experimenters to provide this information is to write some introductory screens that come after the player gives consent, which will tell them what they need to do.

As a researcher, I want to check that participants have read and understood the instructions, so that I have confidence in the data that participants produce. A standard way to do this is to give a "comprehension check" mini-quiz after presenting the information that participants must get correct in order to continue. 

## Outline
A notional draft of the order of the order of screens is as follows:
1. What will you be asked to do (this needs to be detailed enough that we clearly communicate expectations about live video chat with other participants about a potentially difficult topic, and concise enough that it gets read)
  - how long it will take
  - what you will need to do 
    - possibly have some pre-discussion training
    - have a conversation using a live video chat interface with other real people
    - possibly write about your group's answer
    - answer survey questions
  - how you will be paid

2. How to set up your webcam and check that you are ready to participate in the discussion
- see https://github.com/Watts-Lab/deliberation-empirica/issues/7

3. Comprehension Check
 - Which of the following tasks will you be asked to do? (multi-select checkboxes)
 - How will we use your responses? (multi-select checkboxes)
 - How will we use your video data? (multi-select checkboxes)
 - How long is the commitment? (single-select radio buttons)

## Resources
- These screens should be consistent with what we mentioned in the IRB: https://github.com/Watts-Lab/deliberation-project/blob/main/docs/IRB/Deliberation_IRB_submission.pdf
- Examples of how we've done this in the past are here: 
  1. detective game 
    - [documentation](https://github.com/JamesPHoughton/interdependent-diffusion/blob/master/paper/supplement.pdf) Section 3.2.2  
    - code 1: https://github.com/JamesPHoughton/interdependent-diffusion/blob/master/experiment/experiment/client/intro/InstructionStepOne.jsx
    - code 2: https://github.com/JamesPHoughton/interdependent-diffusion/blob/master/experiment/experiment/client/intro/InstructionStepOneb.jsx
    - code 3: https://github.com/JamesPHoughton/interdependent-diffusion/blob/master/experiment/experiment/client/intro/InstructionStepTwo.jsx  
  2. Guess the Correlation Game
    - code 1: https://github.com/amaatouq/guess-the-correlation/blob/master/client/intro/Overview.jsx
    - code 2: https://github.com/amaatouq/guess-the-correlation/blob/master/client/intro/Quiz.jsx 

#### Implementation
Each intro screen lives in its own `.jsx` file in `/client/src/intro-exit`. To insert the intro screen to the training order, import and add it to the list in `/client/src/App.jsx`:
```
<GameFrame introSteps={[Introduction, extraIntroStep1, extraIntroStep2]} exitSteps={[ExampleExitSurvey]}>
```
(And please use better names for the components than `extraIntroStep1`)

# Notes
It may be worth looking in the literature to see if there are examples of instructions other people have used for online video chat discussions in academic work, such as in focus groups, that we can use as a point of comparison. References to those resources can be added to this issue thread.

The comprehension check shouldn't punish people who get it wrong, they should have a chance to go back and try again as many times as they like before they get it right. But, the comprehension check also serves to filter out low-effort participants who are not willing to put in the effort to read. These participants are likely to drop out when they fail to pass the comprehension check. In general, this is good, because we don't want them to get assigned to groups if they aren't willing to participate. (There are also bots that this will help screen, generally they are low in number but high in annoyingness).

# Related issues
- https://github.com/Watts-Lab/deliberation-project/issues/9
- https://github.com/Watts-Lab/deliberation-empirica/issues/7

# Ready to close when
- [x] We have designed a set of intro screens that properly describe what we participants must do
- [x] We have a comprehension check quiz to see if the participants understood the instructions properly
- [x] We have a cypress test to check that participants who pass the quiz may continue
- [x] We have a cypress test to check that those who fail the test can keep trying.
- [ ] @emmaarsekin reviews for clarity

**Comment by kepstein23** [comment]
Do we have an existing time estimate to put in, or should I pull it from the duration of the game and add like 5 minutes for the exit survey/waiting for others to join?

**Comment by JamesPHoughton** [comment]
Good point, if the duration is a treatment variable, then we won't know the precise value until the game launches. Let's say a 10-30 min discussion.

**Comment by kepstein23** [comment]
@JamesPHoughton Should the participant have unlimited attempts on the comprehension check or should they be booted if they get a question wrong?

**Comment by JamesPHoughton** [comment]
Yes, they can have infinite retries. In theory, this means that some folks could get through who are just mashing buttons and not paying attention, but in practice, they tend to drop out. One thing I do in the comprehension check is to include several clearly wrong answers (e.g. Which of the following tasks will you be asked to do: "eat a dishwasher") and some plausible but wrong answers (e.g. "Write an essay about your childhood"). The bots will fail on both, and the inattentive will fail on the second but possibly wake up and then get it right.
