### ISSUE TITLE
"Leave the Room" button?

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#423]
(Thanks to @sky1113 for thinking through this and proposing a solution!)

# Overview
In our Deliberation experiments, we currently have no way of allowing individuals to remove themselves from the discussion while allowing us to record why they left. If people want to leave the discussion, they can always close the browser window - but from our perspective, this looks identical to a network or computer failure. However, if people are purposefully leaving to avoid heated discussions or abusive behavior, we need to know that.

# Possible solution
We are considering implementing a “Leave the Room” button on each stage with active discussion. Clicking this button would close the video-call window, so that participants could neither see nor be seen by other people in the discussion, but they would still be able to participate in the rest of the discussion.

<img width="886" alt="image" src="https://user-images.githubusercontent.com/4304478/217882965-fb46a286-a90e-4ff2-b303-8af8884ed730.png">

Upon clicking the button, participants would receive a popup where they would confirm their choice to leave and be reminded of what this entails.

<img width="634" alt="image" src="https://user-images.githubusercontent.com/4304478/217883160-ff460d0b-1ed7-42e1-99e5-1d824cfaa784.png">

If they continue, they would be led to a new survey screen, where they will be asked to provide a reason for their decision, and after waiting for the experiment to complete (in its normal time), eventually be led to our default exit steps. 

<img width="1107" alt="image" src="https://user-images.githubusercontent.com/4304478/217883445-bfc3ceca-a5d2-4858-ba08-49eea56f6b6c.png">

Participants will still receive pay equivalent to what they would have received for staying in the discussion. If enough other participants remain in the discussion room, the experiment will continue for them as normal. If there are not enough participants, the discussion will end and all participants will be led to the exit steps.

Participants would be made aware of this button and what it entails in the introductory training step of our experiments:

>“In stages where you are asked to actively discuss with others, you will have access to a button labeled ‘Leave the Room.’ Using this button will allow you to exit the discussion while continuing in the experiment. This means that even if you ‘leave the room,’ if you stay for the remainder of the experiment, you will receive full payment. If you choose to use this option, you may be asked additional survey questions regarding your decision.”

# Feedback from you
We would of course love to hear any feedback you have to offer, but we do have a couple of points we would like to highlight to get you started:

- Button Label: Should we label it “Leave the Room?” or something else?
- Ability to Return: Should participants be able to return to the discussion after leaving?
- Feedback Survey: What questions should be included in the survey presented to participants after leaving?

# Related Issues
https://github.com/Watts-Lab/deliberation-empirica/issues/4

**Comment by linneagandhi** [comment]
@JamesPHoughton this is super thoughtful! Curious as to why you want to let them leave the room. Is it for greater external validity? Esp. since you are still paying them for the whole experiment -- it seems odd that they can opt out and just get paid still. Would that create a moral hazard?

**Comment by JamesPHoughton** [comment]
> it seems odd that they can opt out and just get paid
This is on my mind too. One thing that I'm thinking about is that tell them that they can leave the discussion, but in order to be paid they will still need to spend the same amount of time in the experiment. If they leave the room, they go to another survey that asks why they left, but they are still in the same sequence as the rest of the group. They would need to spend the same amount of time with us to get paid.

**Comment by xehu** [comment]
Wow, I think this is really thoughtful. My initial reaction is that this is a great way to collect fine-grained data about failures, as well as being sensitive to people when the discussion gets uncomfortable. A thoughts I have:
- Does the participant get any timer/countdown to know how long they have to wait?
- I'm wondering if there's any way to make the 'leave the room' action more frictionful? I like the idea of making it possible for people to leave if they're uncomfortable, but this needs to be balanced from people exiting out just because they are lazy.

**Comment by JamesPHoughton** [comment]
Notes from the discussion:
- If this is a rare event, do we need to build something special to handle it? 
- Can we instruct them to mute their camera and audio? 
- Add a post-survey if they turned off their cameras, ask them why.

**Comment by JamesPHoughton** [comment]
- Its probably easiest to ask them afterwards "if you muted your webcam, can you tell us why?" 
- would also make it easier to stitch together video and audio clips. 
- Add a reminder at the bottom of the video window that people can step aside by muting their audio and video.
