### ISSUE TITLE
The "Submit" button element should be able to take button text as an argument

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#436]
Currently I believe the button just says "Next". We should be able to override this default in the treatment definition to make it say things like "I'm ready", etc. Should be a pretty easy fix.

For example, say that the treatment file has this syntax:
```yaml
          - type: submitButton
            buttonText: Continue with experiment
            displayTime: 1590

```

### Implementing notes:
- [ ] Need to parse in `client/src/elements/Element.jsx` in the `submitButton` case should take the `buttonText` attribute from the treatment file using syntax `element.buttonText` and pass to <SubmitButton> object.
- [ ] in `client/src/elements/SubmitButton` need to set the inner HTML that currently says `Next` with the optional text, 
- [ ] if there is no optional text, default to `Next`

### Testing
Update the test to check that this works
- [ ] `deliberation-assets/projects/example/treatments.test.yaml` - add a button component with some custom text
- [ ] `cypress/e2e/01_Normal_Paths...` need to check that the button custom text is displayed on the page at the appropriate time.

**Comment by JamesPHoughton** [comment]
Ready to review the PR!

**Comment by mxumary** [comment]
PR here https://github.com/Watts-Lab/deliberation-empirica/pull/481

**Comment by JamesPHoughton** [comment]
Complete in https://github.com/Watts-Lab/deliberation-empirica/pull/481
