### ISSUE TITLE
Turn off browser form autofill

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#478]
In at least one instance, chrome prompted the user to autocomplete the nickname box with credit card info. This would be quite a privacy breach if they did so, and we need to make sure that it doesn't try that.

https://www.w3docs.com/snippets/html/how-to-disable-browser-autocomplete-and-autofill-on-html-form-and-input-fields.html

**Comment by willschulz** [comment]
![Screenshot 2023-03-22 at 10 58 39 AM](https://user-images.githubusercontent.com/51292950/226945870-9e17cd86-73f1-4fa2-9c10-d3495cf44d14.png)

**Comment by willschulz** [comment]
https://stackoverflow.com/questions/15168261/how-does-chrome-detect-credit-card-fields

**Comment by mykoal** [comment]
### What it looks like on Chrome:
![image](https://github.com/Watts-Lab/deliberation-empirica/assets/113119817/b0264fe5-7438-46d4-bd0b-872cea52521d)

### Chrome settings:
![image](https://github.com/Watts-Lab/deliberation-empirica/assets/113119817/bb8135a2-28d4-4144-8bed-86c897bf05ee)

Apparently it only auto-fills your name if you press it

**Comment by mykoal** [comment]
Essentially, just add `autocomplete = "off"` to either the form/input element.

Example code that should work:
`<body>`
`  <form>`
`    <input type = "text"`
`     name = "autocomplete-off"`
`     autocomplete = "off"`
`     >`
`  </form>`
`</body>`
Source: https://www.youtube.com/shorts/h6_EKobmwG8

If that doesn't work, this works too for chrome:
https://www.youtube.com/watch?v=krUHoZJDTsA

**Comment by JamesPHoughton** [comment]
Complete in https://github.com/Watts-Lab/deliberation-empirica/pull/537
Thanks @mykoal
