### ISSUE TITLE
Export metadata for survey & prompt questions

### ISSUE THREAD

**Issue by willschulz** [Watts-Lab/deliberation-empirica#480]
Requests for the exported data:

- [x] the full response scale for each survey/prompt question, and (maybe in future iterations)
- [ ] indicator for whether the response scale is ordered/unordered
- [ ] indicator for whether it’s single- or multiple-response question
- [ ] indicator for whether the order of the response options was fixed, randomly flipped, or scrambled.

**Comment by JamesPHoughton** [comment]
Including the full prompt text and the response options in the data export, along with the metadata. This is everything used to render the prompt, so meets the requirements for scale ordering, question type, and order randomization. 

Addressed in https://github.com/Watts-Lab/deliberation-empirica/pull/670
