### ISSUE TITLE
Production container

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#486]
As a researcher, I want to be able to deploy my experiment as simply as possible, without needing to know too much about DevOps, so that I can focus my effort on the part of the toolset that is enabling science, not the parts that are just overhead.

I want to be able to:
- build a container and push it to the Github Container Registry as a Github Action (https://github.com/Watts-Lab/deliberation-empirica/pkgs/container/deliberation-empirica)
- Deploy the container
- View and store container logs
- View server resource use
- Persist data across server restarts
- Reset everything sometimes

## Old "solution"
So far, I have been using DigitalOcean's [App platform](https://docs.digitalocean.com/products/app-platform/), which takes a dockerfile plus some environment variables and handles almost everything else. This is easy to set up and manage, and has been great for:
- developing in containers
- setting up data storage scripts 
- making sure I have a clean environment each time
- connecting to GH Actions for CI/CD

Unfortunately, DO App Platform [limits the disk space of the container to 2GB](https://docs.digitalocean.com/products/app-platform/details/limits/), which has caused some [problems in production](https://github.com/empiricaly/empirica/issues/269). Ideally, we'd just attach an external file system volume, but DO only lets you [attach S3-like "spaces" or a managed database](https://docs.digitalocean.com/products/app-platform/how-to/store-data/), and we need true file storage for Empirica V2's file-based data storage model.

What i'd love is something with the simplicity of DO's App platform, but just with the ability to mount an arbitrarily large file volume.

## What I've tried
I've tried to move the app to [Azure App Service](https://azure.microsoft.com/en-us/products/app-service) which is the same sort of PAAS model, where you provide a container and they handle most of the rest. The major annoyance with this is that [you can't mount a volume to a path with a `.` character in it](https://stackoverflow.com/questions/60915810/how-to-specify-a-mount-path-with-a-dot-in-azure-web-app-mount-storage) and empirica V2 uses the directory `/.empirica/local` to store the data. This effectively means that I can't mount a volume where I need it on Azure either. 

## Can you help me
- Work out if I can get DO or Azure to do what I need? or...
- Set up something easily manageable on AWS? or...
- Figure out another service I could use that does what I need?

In all honesty, I'm a little wary of AWS, because every time I try and use their stuff, I end up spending a couple days figuring out how to navigate their system, and I don't want to have to employ/be a full-time dev-ops expert to be able to manage and debug the system.

**Comment by shapeseas** [comment]
Some potential steps:
- If in Amazon, likely will need Elastic Container Service (ECS)
- Managed cluster - Fargate; don't have to manage underlying VMs
- Meet with Amazon solutions architect to help with this
- Shawn is going to reach out for ECS consultation with solutions architect. Will join because he's building an experiment with Empirica as well.
- Amazon is offering trainings for small groups mostly targeted to the Wharton computing team; They have done one on ML. If lab is interested we could probably attend
- Terraform - Shawn can send over more info on how they've used it
