### ISSUE TITLE
Allow images from CDN in markdown files

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#520]
It is entirely reasonable to have markdown files that are displayed to participants that include images. We should be able to store these images alongside the markdown files themselves in the CDN, either in the same directory, in some relative directory, or by referencing an absolute path at the CDN root. 

- [x] Add an example of this to the mockCDN included in the main `deliberation-experiment` repo
- [x] Add a test to the cypress `01_Normal_Paths_Omnibus` test that checks that the image loaded properly
- [x] Any changes should be made in `client/src/components/Markdown.jsx`

## Resources
Documentation for react markdown: https://github.com/remarkjs/react-markdown#readme

**Comment by JamesPHoughton** [comment]
- A: Currently having trouble running tests on Windows, Millie and Michael will partner program to use Millies's computer to test, then push and PR.
- B: Alan may have solved this, but some issues with docker. We may need to do a multi-container docker compose, in order to handle the mock cdn.
- C: May be able to use GH Codespace, these may be worth looking at (maybe spend up to 45 mins?)

**Comment by gumillie222** [comment]
When I tried to run cypress test, it seems to be failing in a step before.

<img width="940" alt="Screenshot 2023-07-13 at 3 17 43 PM" src="https://github.com/Watts-Lab/deliberation-empirica/assets/121700352/c7812f37-b22d-4f1b-a0b6-9a849be22b15">

**Comment by JamesPHoughton** [comment]
is it showing the political affiliation survey, before this point? looks like something might be off with the introSequence it's loading. Are you using the mock CDN that is part of the `deliberation-empirica` repo? if its having trouble with that, it may try and use the production CDN, which is probably out of date for that test...

**Comment by gumillie222** [comment]
How do I check if I am using the right mock CDN?

Yes it's right after sound check and enter nickname.

**Comment by JamesPHoughton** [comment]
This might need to be a change to the markdown component that:
1. Looks in the string representing the raw markdown for things formatted as images
2. Replaces the image path with the full path to the CDN version of the image.

**Comment by JamesPHoughton** [comment]
hey @gumillie222, i'm working with a collaborator on a project that needs this, so I'm moving it to higher priority. Can we have a chat sometime to bring me up to speed on what you've done? I may have a chance to look at it soon.

**Comment by JamesPHoughton** [comment]
// Hydrate paths for images in prompt
  text.replace(/\!\[.*\]\((.*)\)/g, (match, path) => {
    const url = useFileURL(path);
    return `![${path}](${url})`;
  });

```js

```
