### ISSUE TITLE
Deliberation Talk notes

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#526]
Please give feedback!

**Comment by markwhiting** [comment]
1. I think the infrastructure and driving decisions for it are so important here but also quite complicated and novel — perhaps people would benefit from a high-level picture upfront. I feel like you say "theres a lot of vagueness" and you close the loop by saying things like "everything is specified in a manifest" but I think that loop is pretty big. I wonder if you could close that loop fast, and then dig into it over a few slides with details and revisit the entire loop again at the end.
2. Just a thought about selection bias, how similar is this bias to the bias of people who actually participate in deliberative activities in society? 
3. The "goals for the first study" feels very technically focused. I wonder if there are 1) biggest problems in this space or 2) areas you are particularly excited by for some narrative reason, or 3) a mechanical goal in the first study, e.g., to demonstrate the mechanism. Personally, I feel like 1 or 2 are stronger motivations for a job market context, i.e., giving a window into your substantive focal areas in addition to your engineering approach.
