### ISSUE TITLE
Bug: Ngrok refreshes page and restarts Jitsi every 5-60 seconds 🐛 🐞 🐜

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#53]
Deploying over ngrok, the page has a tendency to refresh itself on the order of every 5-60 seconds. When the page refreshes (for any reason, even a purposeful restart) the Jitsi client restarts, and kicks me out of the meeting and I'll have to enter again (and in safari, give permissions for the browser to use the webcam again). This makes actual discussions pretty much impossible.

On the local dev server (ie, not over ngrok), the page doesn't refresh at all, and so the connection is completely uninterrupted.

Not sure if the logs are helpful
![image](https://user-images.githubusercontent.com/4304478/170545280-0ca8ed28-2d50-4d15-a494-2c156261a214.png)

**Comment by JamesPHoughton** [comment]
Errors from chrome when the restart happens:
![image](https://user-images.githubusercontent.com/4304478/170558705-5bfb2eb4-fb7c-45aa-8b77-0eb38d9e3320.png)

**Comment by yli12313** [comment]
So what I saw through a test with @JamesPHoughton was the following error that caused the app to refresh and kick out one of the users:

![image](https://user-images.githubusercontent.com/7104719/170558742-67c6b433-020e-4c17-bf7d-bcef0bd44444.png)

**Comment by yli12313** [comment]
We tried again and got the error:

![image](https://user-images.githubusercontent.com/7104719/170561550-33da30e6-1afb-487d-a791-38ec23b10791.png)

**Comment by JamesPHoughton** [comment]
Sounds like the solution from this morning (https://github.com/Watts-Lab/deliberation-project/issues/34) didn't completely do away with the need for port 8844. At least now it's not looking on localhost! 

@npaton - we're looking into reverse proxies that will map two ports on the same URL, not sure if you've done this?

**Comment by npaton** [comment]
Maybe try to disable hmr altogether in the vite config. And any kind of auto refresh.

**Comment by npaton** [comment]
Maybe 'server.hmr: false': https://vitejs.dev/config/#server-hmr

**Comment by JamesPHoughton** [comment]
Even with:
```
server: {
    hmr: false,  // for ngrok deploy. Remove for dev
    port: 8844,
    open: false,
    strictPort: true,
    host: "0.0.0.0",
    ...
  }
```
the client still tries to connect a websocket to 8844, as above, and fails, causing a page refresh. Not sure how to get it to stop, or what triggers that. Looking into if we can set a websocket timeout to be longer than our experiment... =)

**Comment by JamesPHoughton** [comment]
Considering that:
1. Ngrok cannot handle multiple ports on the same hostname, and 
2. multiple ports seem to need to be used in dev mode, and
4. if we can get away from dev mode we should be able to deploy to a proper server

this issue seems moot
