### ISSUE TITLE
Markdown tables not working

### ISSUE THREAD

**Issue by xehu** [Watts-Lab/deliberation-empirica#577]
Tables in Markdown do not appear to render in Deliberation Empirica. An example table (which failed to render in my latest test) is provided below.

| Parties                        |  Amount  |
| ------------------------------ | -------- |
| A alone gets                   | 0        |
| B alone gets                   | 0        |
| C alone gets                   | 0        |
| Just A and B together get      | 118      |
| Just A and C together get      | 84       |
| Just B and C together get      | 50       |
| A, B, and C together get       | 121      |

**Comment by JamesPHoughton** [comment]
@xehu - This is done, if you pull the latest version of main, you should be able to use a table in a prompt.
