### ISSUE TITLE
Have everyone be able to run cypress

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#59]
Everyone run cypress locally:
- [x] @kepstein23 
- [x] @kailyl 
- [x] @bsmith6202 
- [x] @JamesPHoughton 
- [x] @Alan-Qiao 
- [x] @sky1113 
- [x] @isaacgat 

Running cypress in the container turned out to be too much of a hassle. Luckily, we can run the experiment in the container, and develop tests in the normal way, but just run them using a cypress runner running on the host.

We also upgraded to cypress 10.

**Comment by kepstein23** [comment]
@Alan-Qiao I think the way the form is set up in empirica may have changed a bit since we wrote them so that might be the problem. I'll try running them tomorrow with and without docker to see if it's a test problem or docker problem.

**Comment by JamesPHoughton** [comment]
What branch are you working in?

**Comment by Alan-Qiao** [comment]
alan-cypressDocker, I think that's what its called.

**Comment by JamesPHoughton** [comment]
Way to go, team.
