### ISSUE TITLE
Add timestamps to text chat messages

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#602]
Text chat messages currently don't have timestamps. Set the stage number, stage name and the stage elapsed time as message attributes. 

We may need to create a custom chat implementation for this.

**Comment by xehu** [comment]
This should be something already done somewhere --- Mohammed Alsobay's version of PGG has timestamps, but Abdullah's original CSOP data does not. I think the feature was added by someone later, and surely we don't have to reinvent the wheel!
