### ISSUE TITLE
Suggest mturk id in the enter player ID

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#63]
When players enter their ID, we should emphasize that it is so that we as experimenters can ensure that they get paid, and so this should be their MTurk ID. Later on, we ask for their first names or nicknames to display in their video call windows.

**Comment by kepstein23** [comment]
Opened an issue about changing this with empirica here https://github.com/empiricaly/empirica/issues/107

**Comment by JamesPHoughton** [comment]
closed by https://github.com/Watts-Lab/deliberation-empirica/pull/131
