### ISSUE TITLE
Markdown list styling is broken

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#637]
We should be able to display a nested list in a prompt, but it's displaying as a single non-nested list. Not sure if this is a fault of the markdown renderer or the prompt parser.

- item 1
- item 2
  - sub item a
  - sub item b
- item 3 

Not sure if this is the markdown library or how we're using it.

**Comment by JamesPHoughton** [comment]
It looks like this is because we use a special text style for `<h1>`... including `<li>` component, and so that styling is getting applied everywhere there is an LI, and so it isn't distinguishing between nested list items and their parents.

### Potential Solutions:
1. Update our `TextStyles` to include nested list items, and see if we can pass those down to the `Markdown` component
2.  Fix the windii default stylings so that we can get rid of the `TextStyles.jsx` components altogether.

**Comment by JamesPHoughton** [comment]
Might be related to: https://github.com/Watts-Lab/deliberation-empirica/issues/518

Probably related to: 
- https://github.com/Watts-Lab/surveys/issues/119
- https://github.com/Watts-Lab/deliberation-project/issues/107

**Comment by gumillie222** [comment]
- should we get rid of `client/src/components/TextStyles.jsx` at all?
- figure out a way to cypress test

**Comment by JamesPHoughton** [comment]
test case:
```
Markdown to test:

# Heading One
## Heading Two
### Heading Three
#### Heading Four

# Bullet Point List

- item one
- item two
  - subitem a
  - subitem b
    - subsubitem i
    - subsubitem ii
  - subitem c
- item three 

# Numbered List
1. numbered item one
2. numbered item two
    1. numbered subitem one
    2. numbered subitem two
        1. numbered subsubitem one
3. numbered item three
```
Renders:
Markdown to test:

# Heading One
## Heading Two
### Heading Three
#### Heading Four

# Bullet Point List

- item one
- item two
  - subitem a
  - subitem b
    - subsubitem i
    - subsubitem ii
  - subitem c
- item three 

# Numbered List
1. numbered item one
2. numbered item two
    1. numbered subitem one
    2. numbered subitem two
        1. numbered subsubitem one
3. numbered item three
