### ISSUE TITLE
Update name field in video chat to match nickname

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#64]
When a participant joins a chat, their name is displayed in the chat window. We want this name to be the name that we collected earlier in the session, so that we can link player records to video recordings easily, and ensure that we have an accurate record of how people are presenting themselves in the chat. So, we need to take the name set in https://github.com/Watts-Lab/deliberation-empirica/issues/10 and set it as the video call participant name.

## Ready to close when
- [ ] a cypress test checks that the above behavior occurs

**Comment by kepstein23** [comment]
Cypress test will need to use an iframe plugin to access the actual text in the iframe
