### ISSUE TITLE
remove `null` values from open responses in feedback survey postflight report

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#764]
In the postflight report (code here: https://github.com/Watts-Lab/deliberation-empirica/blob/main/server/src/postFlight/postFlightReport.js) we summarize fields that have data from the qc survey to send to the experimenter. Some of these fields can have null or empty values. We should filter these before displaying them.

Fields that can have null values:
- textExpansion
- technicalDetail
- joiningDetail

**Comment by gumillie222** [comment]
If undefined, the array would just be empty. See joiningDetail below:

<img width="673" alt="Screenshot 2024-05-11 at 8 55 15 PM" src="https://github.com/Watts-Lab/deliberation-empirica/assets/121700352/b94f0d6b-23ae-43ba-9b84-d21e8c0900c6">
