### ISSUE TITLE
S2024 3/11

### ISSUE THREAD

**Issue by kepstein23** [Watts-Lab/deliberation-empirica#787]
Mary @mxumary 
- working on mixing audio recordings with ffmpeg
- Next week: have an understanding of ffmpeg file titles
- Stretch goal: have a python script that is clean and fully functional
- @kepstein23 will find her notes on ffmpeg and video names - we will add this documentation somewhere intelligent and easy to fine

Evan @evanping 
- made each element in visualizer editable by clicking
- working on feature to delete elements
- still working on combining add element and add stage in one file @kepstein23 and @evanping will work on this together
- Next week: will work on bug in delete then try to refactor our popups into different

Kimberly @kepstein23 
-  Merged updates into main, cleaned log statements, removed errors and warnings in the console.
- Next week: hoping to work on the timeline and determine how to select a time in the experiment on the visualizer panel

Maya
- working on replications research
- Goal is to have 5 replications done by the end of the semester

Eric @shapeseas 
- set up deliberation locally to show Maya on Wednesday
- sketch out template for blank replication to copy
- sketch out PR template for new replications

Millie @gumillie222 
- have been working on the styling issue #637
- swapped out with self-defined css but some formatting is off -- goal for next week

**Comment by shapeseas** [comment]
@mxumary and @kepstein23 looks like this repository which James sent me as the beginning of documentation in README but then trails off. https://github.com/Watts-Lab/deliberation-video-analysis
