### ISSUE TITLE
 🎯 Spring 4/1 Weekly Meeting

### ISSUE THREAD

**Issue by gumillie222** [Watts-Lab/deliberation-empirica#803]
internship / work experience & words of wisdom
- James: his job carrying paintings
- Kimberly: do things that you don't know how to do because it's not graded
- Millie: don't be scared to reach out
- Mary: be very clear with your manager what your goal is
- Eric: in SF, rent from someone's couch
- Evan: experience working in the pool

Evan
- worked on edit and delete functionalities on stages
- Things to work on: documentation, cypress, yaml transition
- want to learn cypress so will work on that part

Kimberly
- finished basic render panel and basic UI
- next step: figure out how to render different files
- James: import deliberation-empirica

Mary
- audio and video merged but challenge is to merge both
- slight delay in video
- documentation needs some work (goal: get it done but it doesn't have to be perfect)

Millie
- worked on adjusting distances between labels and ticks (pr sent)
- next step: James will look into what issues to work on next

Eric
- met with Maya to review replications
- feedback: make sure structure of replications is in alignment with protocols
- will check Maya's pr to see if it runs correctly
- https://glitch.com/ for testing
- Kimberly will look into Glitch

James
- hanging out with baby girl

**Comment by shapeseas** [comment]
Hey @JamesPHoughton turns out you can't use Docker in Glitch, [as discussed here](https://support.glitch.com/t/can-docker-images-be-installed/46474). Is there a way to run `deliberation-empirica` without docker?
