### ISSUE TITLE
Add a total time breakdown to the postflight report

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#846]
We currently list the time for the intro, countdown, game, and exit stages, but it would also be helpful to list a breakdown for the total time (start to finish), and the total time except for the "countdown" (maybe called "total active time?") in the postflight report.

**Comment by gumillie222** [comment]
a screenshot of the timings portion of post-flight report after adding totalTime and totalActiveTime:

[server]   timings: {
[server]     intro: { max: 12.666, min: 12.022, mean: 12.344000000000001, median: 12.666 },
[server]     countdown: { max: 0.156, min: 0.13, mean: 0.14300000000000002, median: 0.156 },
[server]     lobby: { max: 2.058, min: 1.962, mean: 2.01, median: 2.058 },
[server]     game: { max: 27.143, min: 27.143, mean: 27.143, median: 27.143 },
[server]     exit: { max: 5.438, min: 5.438, mean: 5.438, median: 5.438 },
[server]     totalTime: {
[server]       max: 47.461000000000006,
[server]       min: 46.69500000000001,
[server]       mean: 47.078,
[server]       median: 47.461000000000006
[server]     },
[server]     totalActiveTime: {
[server]       max: 47.30500000000001,
[server]       min: 46.565000000000005,
[server]       mean: 46.935,
[server]       median: 47.30500000000001
[server]     }
[server]   },
