### ISSUE TITLE
Handle game failures with a message to participants

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#85]
Currently, if the game ends for some reason while players are still going through it, the player advances to the exit survey. We should provide an additional page before advancing to the survey apologizing for the error, and then send them to the exit survey.

**Comment by kepstein23** [comment]
Right now if participants get kicked out, they advance to No experiments available.  Do we instead want them to go to a "Sorry, the game is full" screen, then the quality control survey?

**Comment by JamesPHoughton** [comment]
resolved in https://github.com/Watts-Lab/deliberation-empirica/pull/269
