### ISSUE TITLE
Profile bar height problem

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#851]
The profile bar seems to have some weird height issues in the latest experiment. It's taller than it should be and overlaps with the content below it:

![Image](https://github.com/Watts-Lab/deliberation-empirica/assets/4304478/1b6cef6a-923d-471c-a164-4c2fad31786b)

![Image](https://github.com/Watts-Lab/deliberation-empirica/assets/4304478/2df0cd1c-5e4d-4c54-a7f8-3764b1cb6f04)

Not sure if this is margin, pad, or something else (a misplaced newline?).

**Comment by gumillie222** [comment]
I'm not finding any exact places that they overlap, but I do find places where the bottom of the profile bar is very close to the content. I put more space on top in the Stage element.

**Comment by JamesPHoughton** [comment]
I did some work on the CSS, moved the layout CSS for profile into the Game component, which makes it easier to coordinate with other sections.
