### ISSUE TITLE
Switch cypress tests to baseURL

### ISSUE THREAD

**Issue by kepstein23** [Watts-Lab/deliberation-empirica#87]
As a developer, I want to use a baseURL instead of visiting localhost instead in each test so that our tests are written more consistently and we can (maybe) reuse tests with the deployed link easily.

This can be done by setting baseURL in the cypress config file to localhost:300/ and removing localhost:3000/ from all of the visit statements in the tests.

**Comment by JamesPHoughton** [comment]
Working on this in https://github.com/Watts-Lab/deliberation-empirica/tree/james-shorttests
