### ISSUE TITLE
turn off unwanted jitsi features

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#98]
These features exist but we want them to be off by default, so that we can explore their effects as an intervention.

- [x] pin other participants
- [x] boot other participants
- [x] mute other participants
- [x] decide what to do about the volume
- [ ] display talk time statistics

- add a treatment flag for each feature so we can turn them on or off as treatments

**Comment by kepstein23** [comment]
decided to turn off volume
